# Generated by Django 3.2.6 on 2021-08-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('asr', models.IntegerField(default=2000000)),
                ('stock', models.IntegerField(default=1500)),
                ('offers', models.IntegerField(default=20)),
                ('cost', models.FloatField(default=1.5)),
                ('salepx', models.FloatField(default=4.0)),
                ('sales90d', models.IntegerField(default=0)),
            ],
        ),
    ]
