# Generated by Django 3.2.6 on 2021-08-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0002_bookdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='cover',
            field=models.CharField(default='Paperback', max_length=20),
        ),
    ]
