# Generated by Django 3.2.6 on 2021-08-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0003_bookdata_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='isbn13',
            field=models.CharField(max_length=13),
        ),
    ]
