# Generated by Django 3.2.6 on 2021-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0004_alter_bookdata_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
