# Generated by Django 3.2.6 on 2021-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0006_auto_20210828_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsin', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=1)),
                ('salesfees', models.FloatField(default=0)),
                ('postage', models.FloatField(default=0)),
            ],
        ),
    ]
