# Generated by Django 3.2.6 on 2021-08-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0007_salesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('title1', models.CharField(max_length=200)),
                ('datefirstbot', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13)),
                ('quantity', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('cost', models.FloatField(default=1)),
                ('totalprice', models.FloatField(default=1)),
                ('date', models.DateTimeField()),
                ('wholesaler', models.CharField(max_length=1)),
            ],
        ),
    ]
