# Generated by Django 3.2.6 on 2021-09-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappia', '0008_bookstatic_invoicedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
